server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'sam'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'password'
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        type: trace